# Matrices; MML

In [2]:
import numpy as np
np.random.seed(17)
A = np.random.randint(5, size=(2,2)) # 2x2 matrix

### Definition 2.3: Inverse of a Matrix

The determinant $\text{det}(A)$ and the adjacente matrix $A'$ are as follows are used to calculate $A^{-1}$ 
$$A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A)$$
- $(\text{det}(A) = ad - bc)$ (the determinant of ( $A$))
- $(\text{adj}(A))$ is the adjugate of ($A$), which for a $2x2$ matrix is obtained by swapping the diagonal elements and negating the off-diagonal elements.

An important property is the $I$ identity matrix which is computed by $AA^{-1}$

In [3]:
detA = 1/((A[0,0]*A[1,1])-A[0,1]*A[1,0])
Ap = np.array([
        [A[1, 1], -A[0, 1]],
        [-A[1, 0], A[0, 0]]
        ])
Ainv = detA * Ap
id_A = A*Ainv
print(f"Matrix A:\n {A}\n") # 2.21
print(f"Detertminant of A:\n {detA}\n") # exist if is not cero if is cero it does not have an inverse
print(f"Adjugate of A:\n {Ap}\n") # 2.22
print(f"Identity Matrix of A:\n {id_A}\n") # 2.26
print(f"Inverse of A: \n {Ainv}\n") # 2.24
print(f"Comprobate with built-in function: \n {np.linalg.inv(A)}")


Matrix A:
 [[1 1]
 [0 4]]

Detertminant of A:
 0.25

Adjugate of A:
 [[ 4 -1]
 [ 0  1]]

Identity Matrix of A:
 [[ 1.   -0.25]
 [ 0.    1.  ]]

Inverse of A: 
 [[ 1.   -0.25]
 [ 0.    0.25]]

Comprobate with built-in function: 
 [[ 1.   -0.25]
 [ 0.    0.25]]


### Definition 2.4: Transpose
For $A \in \mathbb{R}^{m \times n}$  the matrix $B \in \mathbb{R}^{n \times m}$ with $b_{ij}=a_{ji}$ is called the transpose of A. We write $B = A^T$

In [4]:
B = A.T
print(f"Transpose of A:\n{B}")
print(f"If A is non square the transpose is a bit different")

Transpose of A:
[[1 0]
 [1 4]]
If A is non square the transpose is a bit different


## 2.2.3 Multipilication by a Scalar

__Associativity__:
$$(\lambda \psi)C = \lambda(\psi C), \quad C \in R^{m \times n} \\
\lambda (BC) = (\lambda B)C = B(\lambda C) = (BC)\lambda, \quad B \in R^{m \times n}, C \in R^{n \times k}$$

In [5]:
lam = 2
tsi = 3
print(f"This \n{(lam*tsi)*A} \n is the same as\n{lam*(tsi*A)}") 

This 
[[ 6  6]
 [ 0 24]] 
 is the same as
[[ 6  6]
 [ 0 24]]


This allows us to move scalars around

$(\lambda C)^T=C^T \lambda^T= C^T \lambda = \lambda C^T\; \text{since}\; \lambda=\lambda^T$ for all $\lambda \in \mathbb{R}$

In [6]:
print(f"This \n{(lam*A).T}\n is the same as \n{lam*A.T}")

This 
[[2 0]
 [2 8]]
 is the same as 
[[2 0]
 [2 8]]


__Distributivity__:
$$(\lambda+ \psi)C = \lambda C + \psi C, \quad C \in \mathbb{R}^{m \times n} \\
\lambda(B+C)=\lambda B+ \lambda C, \quad B,C \in \mathbb{R}^{m \times n}$$

In [7]:
print(f"This \n{((lam+tsi)*A)}\n is the same as \n{lam*A + tsi*A}")

This 
[[ 5  5]
 [ 0 20]]
 is the same as 
[[ 5  5]
 [ 0 20]]


### Definition 2.6: Row-Echelon form
- All rows that contain only zeros are at the bottom of the matrix
- Looking at nonzero rows only, the first nonzero number from the left (also called the _pivot_) is always strictly to the right of the pivot of the row above it

In [24]:
rowech = np.array([[1, 1, 1], [0, 3, 1], [0, 0, 1]])
print(rowech,'\nRank:', np.linalg.matrix_rank(rowech)) # in example this is rank 3


[[1 1 1]
 [0 3 1]
 [0 0 1]] 
Rank: 3


### Definition 2.7 Group
A set $\mathcal{G}$ and an operation $\otimes$: $\mathcal{G} \times \mathcal{G}\rightarrow \mathcal{G}$ defined on $\mathcal{G}$. Then $G:=(\mathcal{G}, \otimes)$ is called a group if the following hold:
- Closure (obvio), associativity, neutral element, inverse element 

_Remark_ The inverse element is defined with respect to the operation $\otimes$ and does not mean $1/x$.

In [ ]:
import numpy as np
print(r"Real Numbers Operation (R{\-1}, *)")
def operation(a, b):
    return a*b + a + b
def is_a_group(V):
    '''Function which determines if a vector space is a group or no'''
    V = np.unique(V)
    a, b, c, e = V
    if operation(a, b) not in V:
        print("Closure Failed")
    c = 1
    if not np.isclose(operation(a, operation(b, c)), operation(operation(a, b), c)):
        print("Associativity Failed")
    if operation(a):
        pass
        
V = np.array([-2, 0, 1, 3])
is_a_group(V)

Real Numbers Operation (R{\-1}, *)
Closure Satisfied
Identity Satisfied


## Vector spaces


### Definition 2.9 Vector Space
A real-valued vector space $V =(\mathcal{V}, +,\cdot)$ is a set of $\mathcal{V}$ with two operations 
$$
+: \mathcal{V}\times \mathcal{V} \rightarrow \mathcal{V} \\[5mm]
\cdot : \mathbf{R} \times \mathcal{V} \rightarrow \mathcal{V}
$$
Where 1) ($\mathcal{V}, +$) is an abelian group, 2) with ditributivity 3)Associativity (outer operation) and 4) neutral element with respect to outer operation.

In [1]:
import numpy as np

print(f"--- Example: Vector Space R^2 (using NumPy arrays) ---")

u = np.array([1.0, 2.0])
v = np.array([3.0, -1.0])
w = np.array([-0.5, 1.5])

a = 2.5 # scalars
b = -1.0
one_scalar = 1.0 # multiplicative identity in R

# I. Properties of Vector Addition: (V, +) is an Abelian Group
print("\nI. Properties of Vector Addition:")

# 1. Closure under Addition: u + v must be in V (i.e., a 2D NumPy array)
sum_uv = u + v
print(f"1. Closure: u + v = {sum_uv} (Type: {type(sum_uv)}, Shape: {sum_uv.shape})")


assoc_lhs = (u + v) + w # 2. Associativity of Addition: (u + v) + w == u + (v + w)
assoc_rhs = u + (v + w)
print(f"2. Associativity: (u + v) + w = {assoc_lhs}")
print(f"                  u + (v + w) = {assoc_rhs}")
print(f"                  Are they equal? {np.array_equal(assoc_lhs, assoc_rhs)}")

# 3. Neutral Element of Addition (Zero Vector): There exists 0_vec in V s.t. u + 0_vec = u
zero_vector = np.array([0.0, 0.0]) # or np.zeros_like(u)
print(f"3. Neutral Element (Zero Vector): 0_vec = {zero_vector}")
print(f"   u + 0_vec = {u + zero_vector}")
print(f"   Is it u? {np.array_equal(u + zero_vector, u)}")

# 4. Inverse Element of Addition (Additive Inverse): For u, there's -u s.t. u + (-u) = 0_vec
neg_u = -u
print(f"4. Inverse Element for u: -u = {neg_u}")
print(f"   u + (-u) = {u + neg_u}")
print(f"   Is it 0_vec? {np.array_equal(u + neg_u, zero_vector)}")

# 5. Commutativity of Addition: u + v == v + u
sum_vu = v + u
print(f"5. Commutativity: u + v = {sum_uv}")
print(f"                  v + u = {sum_vu}")
print(f"                  Are they equal? {np.array_equal(sum_uv, sum_vu)}")


# --- II. Properties of Scalar Multiplication & Interaction ---
print("\nII. Properties of Scalar Multiplication & Interaction:")

# 6. Closure under Scalar Multiplication: a * u must be in V
scaled_u = a * u
print(f"6. Closure (Scalar Mult): a * u = {scaled_u} (Type: {type(scaled_u)}, Shape: {scaled_u.shape})")
# NumPy's scalar-array multiplication handles this.

# 7. Distributivity: a * (u + v) == a * u + a * v
dist1_lhs = a * (u + v)
dist1_rhs = (a * u) + (a * v)
print(f"7. Distributivity (scalar over vector add): a * (u + v) = {dist1_lhs}")
print(f"                                          a * u + a * v = {dist1_rhs}")
print(f"                                          Are they equal? {np.array_equal(dist1_lhs, dist1_rhs)}")

# 8. Distributivity: (a + b) * u == a * u + b * u (a+b is scalar addition)
scalar_sum_ab = a + b # This is standard float addition
dist2_lhs = scalar_sum_ab * u
dist2_rhs = (a * u) + (b * u)
print(f"8. Distributivity (vector over scalar add): (a + b) * u = {dist2_lhs}")
print(f"                                          a * u + b * u = {dist2_rhs}")
print(f"                                          Are they equal? {np.array_equal(dist2_lhs, dist2_rhs)}")

# 9. Associativity of Scalar Multiplication: a * (b * u) == (a * b) * u (a*b is scalar mult)
scalar_prod_ab = a * b # This is standard float multiplication
assoc_scalar_lhs = a * (b * u)
assoc_scalar_rhs = scalar_prod_ab * u
print(f"9. Associativity (Scalar Mult): a * (b * u) = {assoc_scalar_lhs}")
print(f"                                (a * b) * u = {assoc_scalar_rhs}") # a*b is scalar multiplication
print(f"                                Are they equal? {np.array_equal(assoc_scalar_lhs, assoc_scalar_rhs)}")

# 10. Neutral Element (Scalar Mult): 1 * u == u
identity_scaled_u = one_scalar * u
print(f"10. Neutral Element (Scalar Mult): 1 * u = {identity_scaled_u}")
print(f"                                   Is it u? {np.array_equal(identity_scaled_u, u)}")

print("\nConclusion: R^2 with standard vector addition and scalar multiplication (as implemented by NumPy) "
      "forms a real-valued vector space.")

--- Example: Vector Space R^2 (using NumPy arrays) ---

I. Properties of Vector Addition:
1. Closure: u + v = [4. 1.] (Type: <class 'numpy.ndarray'>, Shape: (2,))
2. Associativity: (u + v) + w = [3.5 2.5]
                  u + (v + w) = [3.5 2.5]
                  Are they equal? True
3. Neutral Element (Zero Vector): 0_vec = [0. 0.]
   u + 0_vec = [1. 2.]
   Is it u? True
4. Inverse Element for u: -u = [-1. -2.]
   u + (-u) = [0. 0.]
   Is it 0_vec? True
5. Commutativity: u + v = [4. 1.]
                  v + u = [4. 1.]
                  Are they equal? True

II. Properties of Scalar Multiplication & Interaction:
6. Closure (Scalar Mult): a * u = [2.5 5. ] (Type: <class 'numpy.ndarray'>, Shape: (2,))
7. Distributivity (scalar over vector add): a * (u + v) = [10.   2.5]
                                          a * u + a * v = [10.   2.5]
                                          Are they equal? True
8. Distributivity (vector over scalar add): (a + b) * u = [1.5 3. ]
                 

### Outer and Inned product
If dimensions of vectors do not match, only the following multiplications for vectors are defined $ab^T \in \mathbb{R}^{n \times n}$ (outer product) and $a^Tb \in \mathbb{R}$ (inner product)

In [9]:
a = np.array([2, 2, 2, 2, 2])
b = np.array([1, 2, 3, 4, 5])
inner = a.T @ b
outer = a.reshape(-1, 1) @ b.reshape(1, -1) # same as np.outer(a,b) and a @ b.T (theoretically)
print(f"The inner product\n{inner}\n is the same as the dot product \n{np.dot(a, b)}\n")
print(f"The outer product is a matrix as said above: \n{outer}")

The inner product
30
 is the same as the dot product 
30

The outer product is a matrix as said above: 
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]


## Basis and Rank
### Definition 2.13 Basis
Consider a vector space $V=(\mathcal{V},+,\cdot)$ and $\mathcal{A}⊆\mathcal{V}$. A generating set of $\mathcal{A}$ of V is called _minimal_ if there exists no smaller set. Every linearly independent generating set of V is minimal and is called a basis of V.
- A basis is a minimal generating set and a maximal linearly independent set of vectors.

### Definition 2.14 Rank
The number of linearly independent columns of a matrix $A ∈ R^{m×n}$
equals the number of linearly independent rows and is called the rank of $A$ and is denoted by $rk(A)$.

In [10]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Compute column space basis (non-zero pivots in RREF)
U, s, Vt = np.linalg.svd(A)
rank = np.sum(s > 1e-10)  # Numerical tolerance
basis = U[:, :rank]
print("Basis for column space:\n", basis)
rank = np.linalg.matrix_rank(A)
print(f"Since the third row is a linear combination of the first two \n{A}")
print("Rank of A:", rank)  # Output: 2

Basis for column space:
 [[-0.21483724  0.88723069]
 [-0.52058739  0.24964395]
 [-0.82633754 -0.38794278]]
Since the third row is a linear combination of the first two 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of A: 2


### Definition 2.15: Linear mapping
For vector spaces $V, W$ a mapping $\phi: V \rightarrow W$ is called a linear mapping (or vector space homomorphism/linear transformation) if
$$\forall x, y \in V \forall \lambda, \psi \in \mathbb{R}: \phi(\lambda x + \psi y) $$

In [11]:
# \phi is the transformation matrix A
A = np.array([[2,1], [0, 3]])
# vectors
x = np.array([1, 2])
y = np.array([3, 4])
# scalars
lam = 2
psi = -1
# linear mapping 
phi_x = A @ x
phi_y = A @ y
# linearity
lhs = A @ (lam*x + psi * y)
rhs = lam * phi_x  + psi * phi_y

print("φ(λx + ψy):", lhs)
print("λφ(x) + ψφ(y):", rhs)
print("Linearity holds:", np.allclose(lhs, rhs))

φ(λx + ψy): [-2  0]
λφ(x) + ψφ(y): [-2  0]
Linearity holds: True


### Definition 2.15 Injective, Surjective, Bijective
Consider a mapping $\phi:\mathcal{V}\rightarrow \mathcal{W}$ where $\mathcal{V}$, $\mathcal{W}$ can be arbitrary sets, then $\phi$ is called

- _Injective_ (one-to-one) if $\forall x, y\in \mathcal{V}:\phi(x)\Rightarrow x=y$

__if every element__ in the codomain of $\mathcal{W}$ is mapped by at most one element in the domain $\mathcal{V}$, "no two different inputs map to the same output. No "collisions" in the output".
- _Surjective_ if (onto) $\phi(\mathcal{V})=\mathcal{W}$ 

__if every element__ in the codomain $\mathcal{W}$ is mapped by at least one element in the domain $\mathcal{V}$,  "the function "hits" every possible output value in the codomain. The range of the function is equal to its codomain"
- _Bijective_ (one-to-one and onto) if it is injective and surjective. "There's a perfect, one-to-one correspondence between elements of the domain and elements of the codomain. Every input maps to a unique output, and every possible output is hit exactly once."

If $\phi$ is surjective, then every element in $\mathcal{W}$ can be "reached" from $\mathcal{V}$ using $\phi$. A bijective $\phi$ can be "undone", this mapping $\psi$ is then called the inverse of $\phi$ 

In [ ]:
def f(n,t):
    l=len
    d,c=zip(*set(t)) # to work with unique mapping pairs
    x=l(set(c))
    return (x+l(set(d))==l(c)*2)+(x==n)*2 

print(f(2, [(1,2),(2,1)])==3)# => bijective
print(f(2, [(1,1),(1,2)])==2)# => surjective
print(f(3, [(1,1)])==1)# => injective
print(f(3, [(1,2),(2,3)])==1)# => injective
print(f(4, [(1,2),(2,2),(3,2),(4,2)])==0) # => nothing
print(f(2, [(1,2),(1,2)])==1)# => injective
print(f(3, [(1,1),(1,2),(1,3)])==2)# => surjective
print(f(2, [(1,1),(1,1),(2,2)])==3)# => bijective

True
True
True
True
True
True
True
True


- Isomorphism: $\phi:V\rightarrow W$ linear and bijective
- Endomorphism: $\phi:V\rightarrow V$ linear
- Automorphism: $\phi:V\rightarrow V$ linear and bijective


In [ ]:
def phi_R2_to_C(vector_r2):
    """
    Implements the mapping Φ: R^2 → C, where Φ((x1, x2)) = x1 + i*x2.
    Args:
        vector_r2 (np.array): A 2D NumPy array representing (x1, x2).
    Returns:
        complex: The complex number x1 + i*x2.
    """
    if not isinstance(vector_r2, np.ndarray) or vector_r2.shape != (2,):
        raise ValueError("Input must be a 2D NumPy array, e.g., np.array([x1, x2])")
    return vector_r2[0] + 1j * vector_r2[1]

x = np.array([1.0, 2.0]) # (1, 2)
y = np.array([3.0, 4.0]) # (3, 4) 

lhs_additivity = phi_R2_to_C(x + y)
rhs_additivity = phi_R2_to_C(x) + phi_R2_to_C(y)

print(f"x = {x}, y = {y}")
print(f"Φ(x) = {phi_R2_to_C(x)}")
print(f"Φ(y) = {phi_R2_to_C(y)}")
print(f"x + y = {x + y}")
print(f"Φ(x + y) = {lhs_additivity}")
print(f"Φ(x) + Φ(y) = {rhs_additivity}")

x = [1. 2.], y = [3. 4.]
Φ(x) = (1+2j)
Φ(y) = (3+4j)
x + y = [4. 6.]
Φ(x + y) = (4+6j)
Φ(x) + Φ(y) = (4+6j)


### Theorem 2.17 Finite-dimensional vector spaces V and W are isomorphic if and only if $\text{dim}(V)=\text{dim}(W)$
Theorem 2.17 states that there exists a linear, bijective mapping be￾tween two vector spaces of the same dimension. Intuitively, this means
that vector spaces of the same dimension are kind of the same thing, as
they can be transformed into each other without incurring any loss.

In [ ]:
import numpy as np
A = np.array([[1, 2],
              [0, 1]])

print(f"Matrix A defining the isomorphism Phi:\n{A}")
print(f"Determinant of A: {np.linalg.det(A):.1f}") # Should be non-zero
def phi(v):
    """Applies the isomorphic linear map defined by matrix A."""
    if not isinstance(v, np.ndarray) or v.shape != (2,):
        raise ValueError("Input v must be a 2D NumPy array (vector).")
    return A @ v
try:
    A_inv = np.linalg.inv(A)
    print(f"\nInverse of A (for Phi_inverse):\n{A_inv}")
    def phi_inverse(w):
        """Applies the inverse map."""
        if not isinstance(w, np.ndarray) or w.shape != (2,):
            raise ValueError("Input w must be a 2D NumPy array (vector).")
        return A_inv @ w
    has_inverse = True
except np.linalg.LinAlgError:
    print("\nMatrix A is not invertible. Phi is not an isomorphism.")
    has_inverse = False

v_example = np.array([3, 4]) # A vector in V (the domain R^2)
print(f"\nLet v (in V) = {v_example}")

w_mapped = phi(v_example) # w_mapped is in W (the codomain R^2)
print(f"Phi(v) = A @ v = {w_mapped} (this is w in W)")

if has_inverse:
    v_reconstructed = phi_inverse(w_mapped)
    print(f"Phi_inverse(w) = A_inv @ w = {v_reconstructed}")
    # Check if we get back the original v
    print(f"Is v_reconstructed close to v_example? {np.allclose(v_reconstructed, v_example)}")

Matrix A defining the isomorphism Phi:
[[1 2]
 [0 1]]
Determinant of A: 1.0

Inverse of A (for Phi_inverse):
[[ 1. -2.]
 [ 0.  1.]]

Let v (in V) = [3 4]
Phi(v) = A @ v = [11  4] (this is w in W)
Phi_inverse(w) = A_inv @ w = [3. 4.]
Is v_reconstructed close to v_example? True

Conclusion:
Since Phi is a linear transformation represented by an invertible matrix
between two vector spaces of the same dimension (dim=2),
Phi is an isomorphism. This demonstrates that R^2 is isomorphic to R^2
(which is obvious, but the map A makes it a non-trivial isomorphism).
This aligns with Theorem 2.17.


### Exercises

1. Angle between
$$\mathbf{u} = \begin{pmatrix} 1 \\ 0 \\ -1 \\ 2 \end{pmatrix} \quad \text{and} \quad \mathbf{v} = \begin{pmatrix} 3 \\ 1 \\ 0 \\ 1 \end{pmatrix}$$

In [13]:
import torch 
u = torch.tensor([1, 0, -1, 2], dtype=torch.float32)
v = torch.tensor([3, 1, 0, 2], dtype=torch.float32)
def angle(v, w):
    return torch.acos(v.dot(w) / (torch.norm(v) * torch.norm(w)))
angle(u, v)

tensor(0.7017)

2. True or false: $\begin{pmatrix} 1 & 2 \\ 0 &1  \end{pmatrix}$ and $\begin{pmatrix} 1 & -2 \\ 0 &1  \end{pmatrix}$ are inverses of one another?

In [14]:
M = torch.tensor([[1, 2], [0, 1]], dtype=torch.float32)
detM = 1/((M[0,0]*M[1,1])-M[0,1]*M[1,0])
Mp = torch.tensor([
        [M[1, 1], -M[0, 1]],
        [-M[1, 0], M[0, 0]]
        ])
Minv = detM * Mp
print(Minv)

tensor([[ 1., -2.],
        [-0.,  1.]])


In [15]:
M = torch.tensor([[1, -2], [0, 1]], dtype=torch.float32)
detM = 1/((M[0,0]*M[1,1])-M[0,1]*M[1,0])
Mp = torch.tensor([
        [M[1, 1], -M[0, 1]],
        [-M[1, 0], M[0, 0]]
        ])
Minv = detM * Mp
print(Minv)

tensor([[1., 2.],
        [-0., 1.]])


__True__

3. Suppose that we draw a shape in the plane with area  100m2 . What is the area after transforming the figure by the matrix $$\begin{pmatrix} 2 & 3 \\ 1 &2  \end{pmatrix}$$

In [16]:
import numpy as np
# transformation matrix
A = np.array([[2, 3],
              [1, 2]])
det_A = np.linalg.det(A)
original_area = 100

new_area = abs(det_A) * original_area
print(f"The new area is: {new_area} m²")

The new area is: 100.0 m²


4. Check if these three matrices are linearly dependent. 

In [17]:
import numpy as np

# Define the sets of vectors
set1 = np.array([[1, 2, 3],
                 [0, 1, 1],
                 [-1, -1, 1]])

set2 = np.array([[3, 1, 0],
                 [1, 1, 0],
                 [1, 1, 0]])

set3 = np.array([[1, 0, 1],
                 [1, 1, 0],
                 [0, -1, 1]])

def is_linearly_independent(matrix):
    # compute the rank of the matrix
    rank = np.linalg.matrix_rank(matrix) # maximum number of linearly independent rows or columns
    # check if rank equals the number of columns (vectors)
    return rank == matrix.shape[1]

# Check each set
print("Set 1 is linearly independent:", is_linearly_independent(set1))
print("Set 2 is linearly independent:", is_linearly_independent(set2))
print("Set 3 is linearly independent:", is_linearly_independent(set3))

Set 1 is linearly independent: True
Set 2 is linearly independent: False
Set 3 is linearly independent: False


5. Suppose that you have a matrix written as  A=[cd]⋅[ab]  for some choice of values  a,b,c , and  d . True or false: the determinant of such a matrix is always  0 ?

In [18]:
u = np.array([1, 2]).reshape(-1, 1)
v = np.array([3, 4])
A = u * v
np.linalg.det(A)

0.0

6. The vectors  e1=[10]  and  e2=[01]  are orthogonal. What is the condition on a matrix  A  so that  Ae1  and  Ae2  are orthogonal?
$$\boxed{A^TA=I}$$

7. How can you write  tr(A4)  in Einstein notation for an arbitrary matrix  A ?
$$\boxed{\text{tr}(A^4)=A_{ik}A_{kl}A_{lm}A_{mi}}$$